---
name: CI

on: push

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"

      - name: Install pandoc
        run: |
          sudo apt-get install pandoc

      - name: Build Presentation
        run: |
          make
          sed '/.*pdf$/d' .gitignore #otherwise .gitignore excludes html output
          touch .nojekyll #Needed to stop github rendering the talks
          mv slides.html index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
