---
name: CI

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"

      - name: Setup Python
        uses: "actions/setup-python@v1"
        with:
          python-version: "3"

      - name: Install pandoc
        run: |
          sudo apt-get install pandoc

      - name: Build
        run: make
