---
name: CI

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"
      - name: Build
        run: make
        uses: docker://pandoc/core:2.9
