---
name: CI

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"

      - name: Setup Python
        uses: "actions/setup-python@v1"
        with:
          python-version: "3"

      - name: Install pandoc
        run: |
          sudo apt-get install pandoc

      - name: Build
        run: |
          make
          rm .gitignore *.md #otherwise .gitignore excludes html output
          touch .nojekyll# #Needed to stop github rendering the talks

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
